---
# tasks file for ansible-role-network

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Ethernet
- name: Create the network configuration file for ethernet devices.
  template: src=ethernet.j2 dest={{ network_config_path }}/ifcfg-{{ item.device }}
  with_items: "{{ network_ethernet_interfaces }}"
  when: network_ethernet_interfaces is defined
  register: ethernet_result

# Bridge
- name: Create the network configuration file for bridge devices.
  template: src=bridge.j2 dest={{ network_config_path }}/ifcfg-{{ item.device }}
  with_items: "{{ network_bridge_interfaces }}"
  when: network_bridge_interfaces is defined
  register: bridge_result

- name: Create the network configuration file for port on the bridge devices.
  template: src=bridge_port.j2 dest={{ network_config_path }}/ifcfg-{{ item.1 }}
  with_subelements:
   - "{{ network_bridge_interfaces }}"
   - ports
  when: network_bridge_interfaces is defined

# Bonding
- name: Create the network configuration file for bond devices.
  template: src=bond.j2 dest={{ network_config_path }}/ifcfg-{{ item.device }}
  with_items: "{{ network_bond_interfaces }}"
  when: network_bond_interfaces is defined
  register: bond_result

- name: Make sure the bonding module is loaded
  modprobe: name=bonding state=present
  when: bond_result|changed

- name: Create the network configuration file for slave in the bond devices.
  template: src=bond_slave.j2 dest={{ network_config_path }}/ifcfg-{{ item.1 }}
  with_subelements:
   - "{{ network_bond_interfaces }}"
   - bond_slaves
  when: network_bond_interfaces is defined

# Restart Network
- name: Restart Networking.
  service: name=network state=restarted
